連絡先の追加
kigyokusai2022/kigyoku.com pull request #34
Opened 2022-08-24 12:18 UTC by suzu928

写真の著作権云々あるかもしれないからよろしく。一応終わった

2022-08-24 16:13 UTC, matsukun279 requested changes
アイコンはリンク先にあるものを使ってほしい

2022-08-24 16:13 UTC, matsukun279 commented on css/contact.css
> +.contact {
contact-elementのほうがわかりやすい

2022-08-24 16:13 UTC, matsukun279 commented on css/contact.css
> +.contact {
.クラス名::before {}で要素の左に画像を載せたりできるからそれでアイコンの配置をして欲しい。

2022-08-24 16:13 UTC, matsukun279 commented on index.html
> +<section id="contact">
cssでアイコンをつける

2022-08-24 16:13 UTC, matsukun279 commented on index.html
> +    <p><img class="contact" src="img/mail.png">メールアドレス<br>&emsp;&emsp;<a href="mailto:info@kigyoku.com">info@kigyoku.com</a></p>
メールアドレスっていう文字列いらない

2022-08-24 16:13 UTC, matsukun279 commented on index.html
> +    <p><a href="https://twitter.com/kigyokusai"><img class="contact" src="img/twitter.png">   twitter</a></p>
twitterじゃなくて@kigyokusai

2022-08-24 16:13 UTC, matsukun279 commented on index.html
> +    <p><a href="https://www.instagram.com/kigyokusai/"><img class="contact" src="img/instagram.jpg">   Instagram</a></p>
Instagramじゃなくてkigyokusai

2022-08-24 16:13 UTC, matsukun279 commented
使ってほしいアイコン

https://drive.google.com/open?id=1O0BbV5t-g0SJAfc6BrOAQujIfrmPyDfd&authuser=kigyokusai.pub%40gmail.com&usp=drive_fs

2022-08-26 02:15 UTC, aki32585 reviewed
連絡先よりお問い合わせ先のほうがいいかなと思った

2022-08-26 06:22 UTC, suzu928 commented
確かに
しらんけど

> 連絡先よりお問い合わせ先のほうがいいかなと思った

2022-08-26 13:00 UTC, matsukun279 requested changes

2022-08-26 13:00 UTC, matsukun279 commented on index.html
> +    <p><a href="https://twitter.com/kigyokusai"><img class="contact-element" src="img/twitter.png">@kogyokusha</a></p>
@kigyokusai

2022-08-26 13:00 UTC, matsukun279 commented on index.html
> +    <p><a href="https://www.instagram.com/kigyokusai/"><img class="contact-element" src="img/instagram.svg">@kogyokusha</a></p>
kigyokusai

2022-08-26 13:00 UTC, matsukun279 commented on css/contact.css
> +.contact-element {
アイコンと文字の縦の位置がずれているので、text-align: center;かなんかで調整してください。

2022-08-28 09:59 UTC, matsukun279 approved these changes
OK。
縦にずれてる箇所は僕が直します

2022-08-29 12:48 UTC, closed without merging